server:
  address: 0.0.0.0

google:
  sheets:
    application-name: tikitoka-db
    spreadsheet-id: 1_bjbG6TIhPJozYdox5pSg8Voyk6HINAjtGTGYOXeMwI
    credentials-path: ${GOOGLE_APPLICATION_CREDENTIALS:./secrets/tikitoka-495701-927433d85001.json}
    range: Chat!A:E
    news-range: News!A:I

external:
  news-api:
    key: ${NEWS_API_KEY}
    base-url: https://newsapi.org/v2
  solar-api:
    key: ${SOLAR_API_KEY}
    base-url: https://api.upstage.ai/v1/solar
ai:
  service:
    url: ${AI_SERVICE_URL:http://localhost:8000}
    mock: false
